from __future__ import annotations


SUPPLIER_CODES: dict[str, dict[str, float | int | str]] = {
    "SM5": {"name": "Semaglutide", "mg_per_vial": 5, "vials_per_pack": 10},
    "SM10": {"name": "Semaglutide", "mg_per_vial": 10, "vials_per_pack": 10},
    "SM15": {"name": "Semaglutide", "mg_per_vial": 15, "vials_per_pack": 10},
    "SM20": {"name": "Semaglutide", "mg_per_vial": 20, "vials_per_pack": 10},
    "SM30": {"name": "Semaglutide", "mg_per_vial": 30, "vials_per_pack": 10},
    "TR5": {"name": "Tirzepatide", "mg_per_vial": 5, "vials_per_pack": 10},
    "TR10": {"name": "Tirzepatide", "mg_per_vial": 10, "vials_per_pack": 10},
    "TR15": {"name": "Tirzepatide", "mg_per_vial": 15, "vials_per_pack": 10},
    "TR20": {"name": "Tirzepatide", "mg_per_vial": 20, "vials_per_pack": 10},
    "TR30": {"name": "Tirzepatide", "mg_per_vial": 30, "vials_per_pack": 10},
    "TR40": {"name": "Tirzepatide", "mg_per_vial": 40, "vials_per_pack": 10},
    "TR50": {"name": "Tirzepatide", "mg_per_vial": 50, "vials_per_pack": 10},
    "TR60": {"name": "Tirzepatide", "mg_per_vial": 60, "vials_per_pack": 10},
    "RT5": {"name": "Retatrutide", "mg_per_vial": 5, "vials_per_pack": 10},
    "RT10": {"name": "Retatrutide", "mg_per_vial": 10, "vials_per_pack": 10},
    "RT15": {"name": "Retatrutide", "mg_per_vial": 15, "vials_per_pack": 10},
    "RT20": {"name": "Retatrutide", "mg_per_vial": 20, "vials_per_pack": 10},
    "RT30": {"name": "Retatrutide", "mg_per_vial": 30, "vials_per_pack": 10},
    "RT40": {"name": "Retatrutide", "mg_per_vial": 40, "vials_per_pack": 10},
    "RT50": {"name": "Retatrutide", "mg_per_vial": 50, "vials_per_pack": 10},
    "RT60": {"name": "Retatrutide", "mg_per_vial": 60, "vials_per_pack": 10},
    "BC5": {"name": "BPC-157", "mg_per_vial": 5, "vials_per_pack": 10},
    "BC10": {"name": "BPC-157", "mg_per_vial": 10, "vials_per_pack": 10},
    "BT5": {"name": "TB-500", "mg_per_vial": 5, "vials_per_pack": 10},
    "BT10": {"name": "TB-500", "mg_per_vial": 10, "vials_per_pack": 10},
    "CU50": {"name": "GHK-Cu", "mg_per_vial": 50, "vials_per_pack": 10},
    "CU100": {"name": "GHK-Cu", "mg_per_vial": 100, "vials_per_pack": 10},
    "NJ100": {"name": "NAD", "mg_per_vial": 100, "vials_per_pack": 10},
    "NJ500": {"name": "NAD", "mg_per_vial": 500, "vials_per_pack": 10},
    "NJ1000": {"name": "NAD", "mg_per_vial": 1000, "vials_per_pack": 10},
    "GTT": {"name": "Glutathione", "mg_per_vial": 1500, "vials_per_pack": 10},
    "CGL5": {"name": "Cagrilintide", "mg_per_vial": 5, "vials_per_pack": 10},
    "CGL10": {"name": "Cagrilintide", "mg_per_vial": 10, "vials_per_pack": 10},
    "NP810": {"name": "Snap-8", "mg_per_vial": 10, "vials_per_pack": 10},
    "XA5": {"name": "Semax", "mg_per_vial": 5, "vials_per_pack": 10},
    "XA10": {"name": "Semax", "mg_per_vial": 10, "vials_per_pack": 10},
    "SK5": {"name": "Selank", "mg_per_vial": 5, "vials_per_pack": 10},
    "SK10": {"name": "Selank", "mg_per_vial": 10, "vials_per_pack": 10},
    "TSM5": {"name": "Tesamorelin", "mg_per_vial": 5, "vials_per_pack": 10},
    "TSM10": {"name": "Tesamorelin", "mg_per_vial": 10, "vials_per_pack": 10},
    "5AD": {"name": "AOD", "mg_per_vial": 5, "vials_per_pack": 10},
    "10AD": {"name": "AOD", "mg_per_vial": 10, "vials_per_pack": 10},
    "CP10": {"name": "CJC-1295 NO DAC + Ipamorelin", "mg_per_vial": 10, "vials_per_pack": 10},
    "375": {"name": "LL-37", "mg_per_vial": 10, "vials_per_pack": 10},
    "LEMON": {"name": "Lemon Bottle", "mg_per_vial": 10, "vials_per_pack": 10},
    "LC120": {"name": "LC120", "mg_per_vial": 10, "vials_per_pack": 10},
    "LC216": {"name": "LC216", "mg_per_vial": 10, "vials_per_pack": 10},
    "LC600": {"name": "L-Carnitine", "mg_per_vial": 10, "vials_per_pack": 10},
    "CBL60": {"name": "Cerebrolysin", "mg_per_vial": 60, "vials_per_pack": 6},
    "SMO5": {"name": "Sermorelin Acetate", "mg_per_vial": 5, "vials_per_pack": 10},
    "SMO10": {"name": "Sermorelin Acetate", "mg_per_vial": 10, "vials_per_pack": 10},
    "KS5": {"name": "Kisspeptin-10", "mg_per_vial": 5, "vials_per_pack": 10},
    "KS10": {"name": "Kisspeptin-10", "mg_per_vial": 10, "vials_per_pack": 10},
    "BB10": {"name": "BPC-157 + TB-500", "mg_per_vial": 10, "vials_per_pack": 10},
    "BB20": {"name": "BPC-157 + TB-500", "mg_per_vial": 20, "vials_per_pack": 10},
    "KPV5": {"name": "KPV", "mg_per_vial": 5, "vials_per_pack": 10},
    "KPV10": {"name": "KPV", "mg_per_vial": 10, "vials_per_pack": 10},
    "VIP5": {"name": "VIP", "mg_per_vial": 5, "vials_per_pack": 10},
    "VIP10": {"name": "VIP", "mg_per_vial": 10, "vials_per_pack": 10},
    "IG01": {"name": "IGF-1 LR3", "mg_per_vial": 0.1, "vials_per_pack": 10},
    "IG1": {"name": "IGF-1 LR3", "mg_per_vial": 1, "vials_per_pack": 10},
    "IP5": {"name": "Ipamorelin", "mg_per_vial": 5, "vials_per_pack": 10},
    "IP10": {"name": "Ipamorelin", "mg_per_vial": 10, "vials_per_pack": 10},
    "MS10": {"name": "MOTS-c", "mg_per_vial": 10, "vials_per_pack": 10},
    "MS40": {"name": "MOTS-c", "mg_per_vial": 40, "vials_per_pack": 10},
    "ET10": {"name": "Epithalon", "mg_per_vial": 10, "vials_per_pack": 10},
    "ET50": {"name": "Epithalon", "mg_per_vial": 50, "vials_per_pack": 10},
    "DS5": {"name": "DSIP", "mg_per_vial": 5, "vials_per_pack": 10},
    "DS15": {"name": "DSIP", "mg_per_vial": 15, "vials_per_pack": 10},
    "TA5": {"name": "Thymosin Alpha-1", "mg_per_vial": 5, "vials_per_pack": 10},
    "TA10": {"name": "Thymosin Alpha-1", "mg_per_vial": 10, "vials_per_pack": 10},
    "CND5": {"name": "CJC-1295 NO DAC", "mg_per_vial": 5, "vials_per_pack": 10},
    "CND10": {"name": "CJC-1295 NO DAC", "mg_per_vial": 10, "vials_per_pack": 10},
    "CD5": {"name": "CJC-1295 With DAC", "mg_per_vial": 5, "vials_per_pack": 10},
    "2S10": {"name": "SS-31", "mg_per_vial": 10, "vials_per_pack": 10},
    "2S50": {"name": "SS-31", "mg_per_vial": 50, "vials_per_pack": 10},
    "MT1": {"name": "MT1", "mg_per_vial": 10, "vials_per_pack": 10},
    "ML10": {"name": "Melanotan 2", "mg_per_vial": 10, "vials_per_pack": 10},
    "322": {"name": "SLU-PP-322", "mg_per_vial": 5, "vials_per_pack": 10},
    "5AM": {"name": "5-amino-1mq", "mg_per_vial": 5, "vials_per_pack": 10},
    "50AM": {"name": "5-amino-1mq", "mg_per_vial": 50, "vials_per_pack": 10},
    "G25": {"name": "GHRP-2 Acetate", "mg_per_vial": 5, "vials_per_pack": 10},
    "G65": {"name": "GHRP-6 Acetate", "mg_per_vial": 5, "vials_per_pack": 10},
    "G610": {"name": "GHRP-6 Acetate", "mg_per_vial": 10, "vials_per_pack": 10},
    "TY10": {"name": "Thymalin", "mg_per_vial": 10, "vials_per_pack": 10},
    "HA5": {"name": "Hyaluronic Acid", "mg_per_vial": 5, "vials_per_pack": 1},
    "OT2": {"name": "Oxytocin Acetate", "mg_per_vial": 2, "vials_per_pack": 10},
    "P41": {"name": "PT-141", "mg_per_vial": 10, "vials_per_pack": 10},
    "RA10": {"name": "Ara-290", "mg_per_vial": 10, "vials_per_pack": 10},
    "BBG70": {"name": "BPC-157 + GHK-Cu + TB-500", "mg_per_vial": 70, "vials_per_pack": 10},
    "KLOW80": {"name": "GHK-Cu + TB-500 + BPC-157 + KPV", "mg_per_vial": 80, "vials_per_pack": 10},
    "WA3": {"name": "Pure Water", "mg_per_vial": 3, "vials_per_pack": 10},
    "WA10": {"name": "Pure Water", "mg_per_vial": 10, "vials_per_pack": 10},
    "BA3": {"name": "Benzyl Alcohol 0.9%", "mg_per_vial": 3, "vials_per_pack": 10},
    "BA10": {"name": "Benzyl Alcohol 0.9%", "mg_per_vial": 10, "vials_per_pack": 10},
    "AA3": {"name": "Acetic Acid Water 0.6%", "mg_per_vial": 3, "vials_per_pack": 10},
    "AA10": {"name": "Acetic Acid Water 0.6%", "mg_per_vial": 10, "vials_per_pack": 10},
    "ISU": {"name": "Insulin", "mg_per_vial": 3, "vials_per_pack": 1},
    "PI5": {"name": "Pinealon", "mg_per_vial": 5, "vials_per_pack": 10},
    "PI10": {"name": "Pinealon", "mg_per_vial": 10, "vials_per_pack": 10},
    "P20": {"name": "Pinealon", "mg_per_vial": 20, "vials_per_pack": 10},
    "B12": {"name": "B12", "mg_per_vial": 10, "vials_per_pack": 10},
    "AP5": {"name": "Adipotide", "mg_per_vial": 5, "vials_per_pack": 10},
    "G5K": {"name": "HCG", "mg_per_vial": 5000, "vials_per_pack": 10, "unit": "iu"},
    "G10K": {"name": "HCG", "mg_per_vial": 10000, "vials_per_pack": 10, "unit": "iu"},
    "MZ10": {"name": "Mazdutide", "mg_per_vial": 10, "vials_per_pack": 10},
    "SUR10": {"name": "Survodutide", "mg_per_vial": 10, "vials_per_pack": 10},
    "CS5": {"name": "Cagrilintide + Semaglutide", "mg_per_vial": 5, "vials_per_pack": 10},
    "CS10": {"name": "Cagrilintide + Semaglutide", "mg_per_vial": 10, "vials_per_pack": 10},
}


def supplier_lookup(raw_code: str) -> dict[str, float | int | str] | None:
    code = raw_code.strip().upper().replace(" ", "")
    if code in {"柠檬瓶", "LEMONBOTTLE"}:
        code = "LEMON"
    result = SUPPLIER_CODES.get(code)
    if not result:
        return None
    return {"code": code, **result}
